version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "storeApi"
s3_bucket = "sam.ygo.backend"
s3_prefix = "storeApi"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"